export type Locale = "en" | "zh"

export const homeCopy: Record<Locale, Record<string, string>> = {
  en: {
    navGenerator: "Generator",
    navExplainer: "Explainer",
    navExamples: "Examples",
    heroBadge: "AI-Powered Chinese Names",
    heroTitle: "AI Chinese Names Generator & Meaning Explainer",
    heroSubtitle:
      "Explore Chinese names and their meanings. Generate options that match your preferences with cultural and phonetic insights.",
    generatorTitle: "AI Chinese Name Generator",
    generatorDesc: "Provide your preferences and get 3-4 Chinese name options with in-depth analysis.",
    generatorBtn: "Generate",
    explainerTitle: "AI Chinese Name Meaning Explainer",
    explainerDesc: "Enter your Chinese name to get its meaning and cultural context.",
    explainerBtn: "Explain",
    popularNames: "Popular Chinese Names",
    ancientNames: "Ancient Chinese Names",
    familyNames: "Chinese Family Names",
    maleNames: "Chinese Male Names",
    femaleNames: "Chinese Female Names",
  },
  zh: {
    navGenerator: "起名",
    navExplainer: "解名",
    navExamples: "示例",
    heroBadge: "AI 中文起名",
    heroTitle: "AI 中文起名与含义解读",
    heroSubtitle: "输入你的偏好，获取符合音韵、文化与五行的中文名方案，并查看出处与解析。",
    generatorTitle: "AI 中文起名",
    generatorDesc: "填写偏好，生成 3-4 个中文名方案，并附详细解析。",
    generatorBtn: "开始生成",
    explainerTitle: "AI 中文名含义解读",
    explainerDesc: "输入你的中文名，获取含义、文化与出处说明。",
    explainerBtn: "开始解读",
    popularNames: "常见中文名",
    ancientNames: "古风名字",
    familyNames: "姓氏",
    maleNames: "男孩名字",
    femaleNames: "女孩名字",
  },
}

export const generatorCopy: Record<Locale, Record<string, string>> = {
  en: {
    backHome: "← Back to home",
    title: "Generate your Chinese name",
    subtitle: "Fill your preferences to get 3-4 options with phonetics, structure, culture, and Wuxing analysis.",
    surname: "Surname*",
    surnamePlaceholder: "e.g. 李 / 王 / 张",
    gender: "Gender*",
    genderMale: "Boy",
    genderFemale: "Girl",
    birth: "Birth date & time",
    birthHint: "Optional, used for a light Bazi/Wuxing reference",
    length: "Name length",
    single: "Single-character",
    double: "Two-character",
    expectationsLabel: "Parental wishes (multi-select)",
    avoid: "Characters to avoid",
    avoidPlaceholder: "Conflicting characters, homophones, or family duplicates",
    info: "More context helps the model craft better phonetics, culture, and Wuxing suggestions.",
    submit: "Generate names",
    loadingCta: "Generating...",
    loading: "Generating names with AI...",
    loadingHint: "This can take 5–10 seconds. Please keep this tab open.",
    reset: "Reset",
    requiredSurname: "Please enter a surname",
    requiredGender: "Please choose a gender",
    recommendations: "Recommended names",
    analysis: "Deep dive",
    phonetics: "Phonetics",
    structure: "Structure",
    culture: "Culture",
    wuxing: "Wuxing",
    recommendationBadge: "Rec",
    localeLabel: "Language",
  },
  zh: {
    backHome: "← 返回首页",
    title: "生成你的中文名",
    subtitle: "填写偏好后生成 3-4 个方案，并附音律、字形、文化、五行解析。",
    surname: "姓氏*",
    surnamePlaceholder: "如：李、王、张",
    gender: "性别*",
    genderMale: "男孩",
    genderFemale: "女孩",
    birth: "出生日期时辰",
    birthHint: "可选，用于简易八字喜用神参考",
    length: "字数偏好",
    single: "单字",
    double: "双字",
    expectationsLabel: "父母期望（可多选）",
    avoid: "避讳字",
    avoidPlaceholder: "不想要的字或谐音，避免与长辈重复等",
    info: "信息越完整，模型越能给出贴合的音律、文化与五行建议。",
    submit: "生成名字",
    loadingCta: "生成中...",
    loading: "AI 正在生成名字...",
    loadingHint: "可能需要 5-10 秒，请保持页面打开耐心等待。",
    reset: "重置",
    requiredSurname: "请填写姓氏",
    requiredGender: "请选择性别",
    recommendations: "推荐名字",
    analysis: "深度解析",
    phonetics: "音律分析",
    structure: "字形结构",
    culture: "文化出处",
    wuxing: "五行解读",
    recommendationBadge: "推荐",
    localeLabel: "语言",
  },
}

export const explainerCopy: Record<Locale, Record<string, string>> = {
  en: {
    backHome: "← Back to home",
    title: "Explain your Chinese name",
    subtitle: "Enter your Chinese name to get pronunciation, meaning, structure, cultural references, and Wuxing insights.",
    name: "Chinese name*",
    namePlaceholder: "e.g. 李白 / 王菲 / 赵云",
    context: "Context (optional)",
    contextPlaceholder: "Nickname? Dialect? Who gave the name? Any concerns?",
    info: "The more context you provide, the better the explanation.",
    submit: "Explain name",
    loadingCta: "Explaining...",
    loading: "Explaining your name with AI...",
    loadingHint: "This may take a few seconds. Hang tight while we generate the details.",
    reset: "Reset",
    requiredName: "Please enter a Chinese name",
    results: "Name analysis",
    pinyin: "Pinyin",
    meaning: "Meaning",
    structure: "Structure",
    culture: "Culture",
    wuxing: "Wuxing",
    phonetics: "Phonetics",
  },
  zh: {
    backHome: "← 返回首页",
    title: "解读你的中文名",
    subtitle: "输入中文名，获取读音、含义、字形、文化出处与五行解读。",
    name: "中文名*",
    namePlaceholder: "如：李白 / 王菲 / 赵云",
    context: "补充说明（可选）",
    contextPlaceholder: "外号？方言读法？谁起的名字？有什么顾虑？",
    info: "信息越充分，解读越贴合。",
    submit: "开始解读",
    loadingCta: "解读中...",
    loading: "AI 正在解读名字...",
    loadingHint: "可能需要几秒，请耐心等待。",
    reset: "重置",
    requiredName: "请填写中文名",
    results: "名字解析",
    pinyin: "拼音",
    meaning: "含义",
    structure: "字形结构",
    culture: "文化出处",
    wuxing: "五行解读",
    phonetics: "音律",
  },
}
